### ISSUE TITLE
The timer and tie if only have two players

### ISSUE THREAD

**Issue by mohammedsafvan** [arvidsandin/draw-contest#5]
Hi
i really like your game
issue :
->  if we create a room then in playground (play/index.html) the timer starts without an opponent
->  if we have only two players it will end up in tie. because of both drawer and guesser awarded same points at every chance they answer
Thanks

**Comment by arvidsandin** [comment]
Thank you!
I'll see what I can do about the timer.
Regarding the second issue, I feel like the drawer has to be awarded if someone guesses correctly (otherwise the best strategy is to not draw at all) and the same for the guesser (otherwise the best strategy is to not guess at all). If you can think of another solution that would also make two player games better, please share :)

**Comment by arvidsandin** [comment]
A drawer will now not be chosen until a second player joins a room
